runtime_config:
  python_version: 3

instance_class: F4_1G
entrypoint: gunicorn -t 120 -b :$PORT main:app
env: flex
threadsafe: yes

resources:
  cpu: 2
  memory_gb: 2.0
  disk_size_gb: 10

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

